<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Generateur\Api\Representation\GenerationRepresentation[] $resources
 * @var \Generateur\Api\Representation\GenerationRepresentation[] $generations
 * @var \Generateur\Form\QuickSearchForm $formSearch
 * @var \Omeka\Form\ConfirmForm $formDeleteSelected
 * @var \Omeka\Form\ConfirmForm $formDeleteAll
 */

use Generateur\Api\Adapter\GenerationAdapter;

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$hyperlink = $this->plugin('hyperlink');

$this->headLink()->appendStylesheet($this->assetUrl('css/generateur-admin.css', 'Generateur'));
$this->headScript()->appendFile($this->assetUrl('js/generateur-admin.js', 'Generateur'), 'text/javascript', ['defer' => 'defer']);
$this->htmlElement('body')->appendAttribute('class', 'generations browse');

$userIsAllowedBatchUpdate = $this->userIsAllowed(GenerationAdapter::class, 'batch_update');
$userIsAllowedBatchDelete = $this->userIsAllowed(GenerationAdapter::class, 'batch_delete');

$sortHeadings = [
    [
        'label' => $translate('Annotator'),
        'value' => 'name',
    ],
    [
        'label' => $translate('Annotator email'),
        'value' => 'email',
    ],
    [
        'label' => $translate('Resource'),
        'value' => 'resource_id',
    ],
    [
        'label' => $translate('Date generated'),
        'value' => 'created',
    ],
];
?>

<?php echo $this->pageTitle('', 1, $translate('Generations')); ?>

<?php echo $this->searchFilters(); ?>

 <div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $hyperlink($translate('Quick Search'), '#', ['class' => 'search advanced-search']); ?>
    <?php echo $this->sortSelector($sortHeadings); ?>
</div>

<?php $this->trigger('view.browse.before'); ?>
<?php if ($generations): ?>
<form method="post" id="batch-form" class="disable-unsaved-warning">
    <?php if ($userIsAllowedBatchUpdate || $userIsAllowedBatchDelete): ?>
    <div class="batch-inputs">
        <select class="batch-actions-select" name="batch_action" aria-label="<?php echo $translate('Batch actions'); ?>">
            <option value="default"><?php echo $translate('Batch actions'); ?></option>
            <?php if ($userIsAllowedBatchUpdate): ?>
            <option value="update-selected" class="batch-selected" disabled="disabled"><?php echo $translate('Edit selected'); ?></option>
            <option value="update-all"><?php echo $translate('Edit all'); ?></option>
            <?php endif; ?>
            <?php if ($userIsAllowedBatchDelete): ?>
            <option value="delete-selected" class="batch-selected" disabled="disabled"><?php echo $translate('Delete selected'); ?></option>
            <option value="delete-all"><?php echo $translate('Delete all'); ?></option>
            <?php endif; ?>
        </select>
        <div class="batch-actions">
            <button type="button" class="default active" disabled="disabled"><?php echo $translate('Go'); ?></button>
            <?php if ($userIsAllowedBatchUpdate): ?>
            <input type="submit" class="update-selected" value="<?php echo $translate('Go'); ?>" formaction="<?php echo $escape($this->url(null, ['action' => 'batch-edit'], true)); ?>">
            <input type="submit" class="update-all" value="<?php echo $translate('Go'); ?>" formaction="<?php echo $escape($this->url(null, ['action' => 'batch-edit-all'], true)); ?>">
            <?php endif; ?>
            <input type="hidden" name="query" class="batch-query" value="<?php echo $escape(json_encode($this->params()->fromQuery())); ?>">
            <?php if ($userIsAllowedBatchDelete): ?>
            <a class="delete button sidebar-content delete-selected" data-sidebar-selector="#sidebar-delete-selected"><?php echo $translate('Go'); ?></a>
            <a class="delete button sidebar-content delete-all" data-sidebar-selector="#sidebar-delete-all"><?php echo $translate('Go'); ?></a>
            <?php endif; ?>
        </div>
    </div>
    <?php endif; ?>

<table class="tablesaw batch-edit" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th>
                <?php if ($userIsAllowedBatchUpdate || $userIsAllowedBatchDelete): ?>
                <input type="checkbox" class="select-all" aria-label="<?php echo $translate('Select all'); ?>">
                <?php endif; ?>
                <?php echo $translate('Generation'); ?>
            </th>
            <th><?php echo $translate('Targets'); ?></th>
            <th><?php echo $translate('Annotator'); ?></th>
            <th><?php echo $translate('Date generated'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($generations as $generation): ?>
        <?php
        $userIsAllowedUpdate = $generation->userIsAllowed('update');
        $userIsAllowedDelete = $generation->userIsAllowed('delete');
        $resources = $generation->targetSources();
        $owner = $generation->owner();
        ?>
        <tr class="generation">
            <td>
                <?php if ($userIsAllowedBatchUpdate || $userIsAllowedBatchDelete): ?>
                <input type="checkbox" name="resource_ids[]" value="<?php echo $generation->id(); ?>" aria-label="<?php echo $translate('Select item'); ?>"<?php if (!($userIsAllowedUpdate || $userIsAllowedDelete)): ?> disabled="disabled"<?php endif; ?>>
                <?php endif; ?>
                <?php echo $generation->linkPretty(); ?>
                <?php if (!$generation->isPublic()): ?>
                    <span class="o-icon-private" aria-label="<?php echo $translate('Private'); ?>"></span>
                <?php endif; ?>
                <ul class="actions">
                    <?php if ($userIsAllowedUpdate): ?>
                    <li><?php echo $generation->link('', 'edit', [
                        'class' => 'o-icon-edit',
                        'title' => $translate('Edit'),
                    ]); ?></li>
                    <?php endif; ?>
                    <?php if ($userIsAllowedDelete): ?>
                    <li><?php echo $hyperlink('', '#', [
                        'data-sidebar-selector' => '#sidebar',
                        'data-sidebar-content-url' => $generation->url('delete-confirm'),
                        'class' => 'o-icon-delete sidebar-content',
                        'title' => $translate('Delete'),
                    ]); ?></li>
                    <?php endif; ?>
                    <li><?php echo $hyperlink('', '#', [
                        'data-sidebar-selector' => '#sidebar',
                        'data-sidebar-content-url' => $generation->url('show-details'),
                        'class' => 'o-icon-more sidebar-content',
                        'title' => $translate('Details'),
                    ]); ?></li>
                </ul>
            </td>
            <td>
                <?php if ($resources): ?>
                    <?php foreach ($resources as $resource): ?>
                    <?php echo $resource->linkPretty(); ?>
                    <span class="resource-name <?php echo $resource->getControllerName(); ?>" aria-label="<?php echo $translate($resource->getControllerName()); ?>"></span>
                    <?php endforeach; ?>
                <?php else: ?>
                    [<?php echo $translate('Removed'); ?>]
                <span class="resource-name no-resource"></span>
                <?php endif; ?>
            </td>
            <td>
                <span class="<?php if ($owner): ?>generation-user<?php else: ?>generation-public<?php endif; ?>"><?php
                    echo $generation->linkAnnotator();
                ?></span>
                <?php if (!$owner): ?>
                    <span class="o-icon-users" aria-label="<?php echo $translate('Public'); ?>"></span>
                <?php endif; ?>
            </td>
            <td><?php echo $generation->created()->format('Y-m-d H:i:s'); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

</form>

<?php $this->trigger('view.browse.after'); ?>
<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<div id="sidebar" class="sidebar">
    <?php echo $hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $translate('Close'),
    ]); ?>
    <div class="sidebar-content"></div>
</div>

<?php if ($userIsAllowedBatchDelete): ?>
<div id="sidebar-delete-selected" class="sidebar">
    <?php echo $hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $translate('Close'),
    ]); ?>
    <div class="sidebar-content">
        <div id="sidebar-confirm">
            <h3><?php echo $translate('Delete generations'); ?></h3>
            <p><?php echo $translate('Are you sure you would like to delete the selected generations?'); ?></p>
            <p class="error"><?php echo sprintf(
                $translate('%s: this action will permanently delete %s generations and cannot be undone.'),
                sprintf('<strong>%s</strong>', $translate('Warning')),
                '<strong><span id="delete-selected-count"></span></strong>'
            ); ?></p>
            <?php echo $this->form($this->formDeleteSelected); ?>
        </div>
    </div>
</div>
<div id="sidebar-delete-all" class="sidebar">
    <?php echo $hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $translate('Close'),
    ]); ?>
    <div class="sidebar-content">
        <div id="sidebar-confirm">
            <h3><?php echo $translate('Delete generations'); ?></h3>
            <p><?php echo $translate('Are you sure you would like to delete all generations on all pages of this result?'); ?></p>
            <p class="error"><?php echo sprintf(
                $translate('%s: this action will permanently delete %s generations and cannot be undone.'),
                sprintf('<strong>%s</strong>', $translate('Warning')),
                sprintf('<strong>%s</strong>', number_format($this->pagination()->getPaginator()->getTotalCount()))
            ); ?></p>
            <label><input type="checkbox" name="confirm-delete-all-check"> <?php echo $translate('Are you sure?'); ?></label>
            <?php echo $this->form($this->formDeleteAll); ?>
        </div>
    </div>
</div>

<script>
// Complete the batch delete form after confirmation.
$('#confirm-delete-selected, #confirm-delete-all').on('submit', function(e) {
    var confirmForm = $(this);
    if ('confirm-delete-all' === this.id) {
        confirmForm.append($('.batch-query').clone());
    } else {
        $('#batch-form').find('input[name="resource_ids[]"]:checked:not(:disabled)').each(function() {
            confirmForm.append($(this).clone().prop('disabled', false).attr('type', 'hidden'));
        });
    }
});
$('.delete-all').on('click', function(e) {
    Omeka.closeSidebar($('#sidebar-delete-selected'));
});
$('.delete-selected').on('click', function(e) {
    Omeka.closeSidebar($('#sidebar-delete-all'));
    var inputs = $('input[name="resource_ids[]"]');
    $('#delete-selected-count').text(inputs.filter(':checked').length);
});
$('#sidebar-delete-all').on('click', 'input[name="confirm-delete-all-check"]', function(e) {
    $('#confirm-delete-all input[type="submit"]').prop('disabled', this.checked ? false : true);
});
</script>
<?php endif; ?>

<?php else: ?>

<div class="no-resources">
    <p><?php echo $translate('Your query returned no generations.'); ?></p>
</div>

<?php endif; ?>

<div id="sidebar-search" class="sidebar search">
    <?php echo $hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $translate('Close'),
    ]); ?>
    <div class="sidebar-content">
        <div id="sidebar-search-form" class="disable-unsaved-warning">
            <h3><?php echo $translate('Search generations'); ?></h3>
            <?php echo $hyperlink($translate('Advanced search'), $this->url(null, ['action' => 'search'], ['query' => $this->params()->fromQuery()], true), ['class' => 'advanced-search']); ?>
            <?php echo $this->form($formSearch); ?>
        </div>
    </div>
</div>
