<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Generateur\Api\Representation\GenerationRepresentation $resource
 * @var \Generateur\Api\Representation\GenerationRepresentation $generation
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/generateur-admin.css', 'Generateur'));
// $this->headScript()->appendFile($this->assetUrl('js/generateur-admin.js', 'Generateur'), 'text/javascript', ['defer' => 'defer']);

$this->htmlElement('body')->appendAttribute('class', 'generations show');

/*
$sectionNavs = [
    'generation-metadata' => $translate('Metadata'),
    'generation-bodies' => $translate('Bodies'),
    'generation-targets' => $translate('Targets'),
];
*/
?>
<?php echo $this->pageTitle($generation->displayTitle(), 1, $translate('Generations')); ?>
<div id="page-actions">
    <?php if ($generation->userIsAllowed('update')): ?>
    <?php echo $generation->link($translate('Edit generation'), 'edit', ['class' => 'button']); ?>
    <?php endif; ?>
</div>

<?php // Currently, the bodies and the targets are on the same tab. ?>
<?php // echo $this->sectionNav($sectionNavs, 'view.show.section_nav', $generation); ?>

<div id="generation-metadata" class="active section">
    <?php echo $generation->displayValues(); ?>
</div>

<div id="generation-bodies" class="active section">
    <?php $bodies = $generation->bodies(); ?>
    <div class="meta-group">
        <h4 class="generation-caption"><?php echo $translate('Bodies'); ?></h4>
        <?php if (count($bodies)): ?>
            <?php $i = 0; ?>
            <?php foreach ($bodies as $body): ?>
                <div class="value generation-body">#<?php echo ++$i; ?></div>
                <?php if ( $body->resourceClass()): ?>
                    <div class="meta-group">
                        <h4><?php echo $translate('Class'); ?></h4>
                        <div class="value"><?php echo $escape($translate($body->resourceClass()->label())); ?></div>
                    </div>
                <?php endif; ?>
                <?php echo $body->displayValues(); ?>
            <?php endforeach; ?>
        <?php else: ?>
            <p class="no-resources"><?php echo $translate('This generation has no bodies.')?></p>
        <?php endif; ?>
    </div>
</div>

<div id="generation-targets" class="active section">
    <?php $targets = $generation->targets(); ?>
    <div class="meta-group">
        <h4 class="generation-caption"><?php echo $translate('Targets'); ?></h4>
        <?php if (count($targets)): ?>
            <?php $i = 0; ?>
            <?php foreach ($targets as $target): ?>
                <div class="value generation-target">#<?php echo ++$i; ?></div>
                <?php if ( $target->resourceClass()): ?>
                    <div class="meta-group">
                        <h4><?php echo $translate('Class'); ?></h4>
                        <div class="value"><?php echo $escape($translate($target->resourceClass()->label())); ?></div>
                    </div>
                <?php endif; ?>
                <?php // Note: when type + value, it is a selector. ?>
                <?php echo $target->displayValues(); ?>
            <?php endforeach; ?>
        <?php else: ?>
            <p class="no-resources"><?php echo $translate('This generation has no targets.')?></p>
        <?php endif; ?>
    </div>
</div>

<div class="sidebar active">
    <?php echo $this->thumbnail($generation, 'square'); ?>
    <div class="meta-group">
        <h4><?php echo $translate('Visibility'); ?></h4>
        <div class="value"><?php echo ($generation->isPublic()) ? $escape($translate('Public')) : $escape($translate('Private')); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $translate('Created'); ?></h4>
        <div class="value"><?php echo $escape($generation->created()->format('Y-m-d H:i:s')); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $translate('Owner'); ?></h4>
        <div class="value"><?php echo $generation->linkAnnotator(); ?></div>
    </div>

    <?php $this->trigger('view.show.sidebar'); ?>
</div>
<?php $this->trigger('view.show.after'); ?>
