<?php
namespace Generateur\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Event\LifecycleEventArgs;

/**
 * @Entity
 * @HasLifecycleCallbacks
 */
class Generation extends GenerationPart
{
    /**
     * This property simplifies the search inside all the generation parts. It
     * is a copy of the id itself.
     * Because it's autogenerated by the database, it should be nullable in
     * order to be filled in a post persist request. This is needed only during
     * creation, since it will never change.
     * @todo Find a way to keep Generation parent non-nullable and to avoid a post-persist event.
     *
     * @OneToOne(
     *     targetEntity="Generation",
     *     mappedBy="generation",
     *     cascade={"persist"}
     * )
     * @JoinColumn(
     *     name="generation_id",
     *     referencedColumnName="id",
     *     nullable=true
     * )
     */
    protected $generation;

    protected $part = \Generateur\Entity\Generation::class;

    /**
     * @var GenerationTarget[]
     * @OneToMany(
     *     targetEntity="GenerationTarget",
     *     mappedBy="generation",
     *     orphanRemoval=true,
     *     cascade={"persist", "remove", "detach"},
     *     indexBy="id"
     * )
     * @OrderBy({"id" = "ASC"})
     */
    protected $targets;

    /**
     * @var GenerationBody[]
     * @OneToMany(
     *     targetEntity="GenerationBody",
     *     mappedBy="generation",
     *     orphanRemoval=true,
     *     cascade={"persist", "remove", "detach"},
     *     indexBy="id"
     * )
     * @OrderBy({"id" = "ASC"})
     */
    protected $bodies;

    public function __construct()
    {
        parent::__construct();
        $this->generation = $this;
        $this->targets = new ArrayCollection;
        $this->bodies = new ArrayCollection;
    }

    public function getResourceName()
    {
        return 'generations';
    }

    /**
     * @return \Generateur\Entity\GenerationTarget[]
     */
    public function getTargets()
    {
        return $this->targets;
    }

    /**
     * @return \Generateur\Entity\GenerationBody[]
     */
    public function getBodies()
    {
        return $this->bodies;
    }

    public function setGeneration(Generation $generation)
    {
        // Don't set generation: it must be the current one.
    }

    /**
     * @return self
     */
    public function getGeneration()
    {
        return $this;
    }

    /**
     * @PostPersist
     */
    public function postPersist(LifecycleEventArgs $eventArgs)
    {
        // Nothing to do, since $this->generation is already $this.
        // The post persist just needs to be triggered, so the auto-generated id
        // is filled in this column too.
        // $this->generation = $eventArgs->getEntity();
    }
}
