<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Generateur\Api\Representation\GenerationRepresentation[] $resources
 * @var \Generateur\Api\Representation\GenerationRepresentation[] $generations
 */

$translate = $this->plugin('translate');
$assetUrl = $this->plugin('assetUrl');

$this->headLink()
    ->appendStylesheet($assetUrl('vendor/tablesaw/tablesaw.stackonly.css', 'Omeka'))
    ->appendStylesheet($assetUrl('vendor/webui-popover/jquery.webui-popover.min.css', 'Generateur'))
    ->appendStylesheet($assetUrl('css/generateur.css', 'Generateur'));
$this->headScript()
    ->appendFile($assetUrl('vendor/tablesaw/tablesaw.stackonly.jquery.js', 'Omeka'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('vendor/webui-popover/jquery.webui-popover.min.js', 'Generateur'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('js/generateur.js', 'Generateur'), 'text/javascript', ['defer' => 'defer']);

$this->htmlElement('body')->appendAttribute('class', 'generations browse');

$sortHeadings = [
    [
        'label' => $translate('Owner'),
        'value' => 'name',
    ],
    [
        'label' => $translate('Resource'),
        'value' => 'resource_id',
    ],
    [
        'label' => $translate('Date generated'),
        'value' => 'created',
    ],
];
?>

<?= $this->pageTitle('', 1, $translate('Generations')) ?>

<?= $this->searchFilters() ?>

 <div class="browse-controls">
    <?= $this->pagination() ?>
    <?php // echo $this->hyperlink($translate('Advanced search'), $this->url(null, ['action' => 'search'], ['query' => $this->params()->fromQuery()], true), ['class' => 'advanced-search']); ?>
    <?= $this->sortSelector($sortHeadings) ?>
</div>

<?php $this->trigger('view.browse.before'); ?>
<?php if ($generations): ?>
<table class="tablesaw tablesaw-stack" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th>
                <?= $translate('Generation') ?>
            </th>
            <th><?= $translate('Owner') ?></th>
            <th><?= $translate('Date generated') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($generations as $generation): ?>
        <?php
        $owner = $generation->owner();
        ?>
        <tr class="generation">
            <td>
                <?= $generation->linkPretty() ?>
            </td>
            <td>
                <?= $generation->resource()->linkPretty() ?>
                <span class="resource-name <?= $generation->resource()->getControllerName() ?>" aria-label="<?= $translate($generation->resource()->getControllerName()) ?>"></span>
            </td>
            <td>
                <span class="<?php if ($owner): ?>generation-user<?php else: ?>generation-public<?php endif; ?>"><?php
                    echo $generation->owner() ? $generation->owner()->name() : $translate('[removed]');
                ?></span>
            </td>
            <td><?= $generation->created()->format('Y-m-d H:i:s') ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php $this->trigger('view.browse.after'); ?>
<div class="browse-controls">
    <?= $this->pagination() ?>
</div>

<?php else: ?>

<div class="no-resources">
    <p><?= $translate('Your query returned no generations.') ?></p>
</div>

<?php endif; ?>
