<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Generateur\Api\Representation\GenerationRepresentation $resource
 * @var \Generateur\Api\Representation\GenerationRepresentation $generation
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$this->htmlElement('body')->appendAttribute('class', 'generations show');

?>
<?php echo $this->pageTitle($generation->displayTitle(), 2); ?>
<h3><?php echo $translate('Generation'); ?></h3>
<?php $this->trigger('view.show.before'); ?>

<div id="generation-metadata" class="active section">
    <div class="meta-group">
        <h4><?php echo $translate('Owner'); ?></h4>
        <div class="value"><?php echo $generation->linkAnnotator(); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $translate('Created'); ?></h4>
        <div class="value"><?php echo $escape($generation->created()->format('Y-m-d H:i:s')); ?></div>
    </div>
    <h4><?php echo $translate('Metadata'); ?></h4>
    <?php echo $generation->displayValues(); ?>
</div>

<div id="generation-bodies" class="active section">
    <?php $bodies = $generation->bodies(); ?>
    <div class="meta-group">
        <h4 class="generation-caption"><?php echo $translate('Bodies'); ?></h4>
        <?php if (count($bodies)): ?>
            <?php $i = 0; ?>
            <?php foreach ($bodies as $body): ?>
                <div class="value generation-body">#<?php echo ++$i; ?></div>
                <?php if ( $body->resourceClass()): ?>
                    <div class="meta-group">
                        <h4><?php echo $translate('Class'); ?></h4>
                        <div class="value"><?php echo $escape($translate($body->resourceClass()->label())); ?></div>
                    </div>
                <?php endif; ?>
                <?php echo $body->displayValues(); ?>
            <?php endforeach; ?>
        <?php else: ?>
            <p class="no-resources"><?php echo $translate('This generation has no bodies.')?></p>
        <?php endif; ?>
    </div>
</div>

<div id="generation-targets" class="active section">
    <?php $targets = $generation->targets(); ?>
    <div class="meta-group">
        <h4 class="generation-caption"><?php echo $translate('Targets'); ?></h4>
        <?php if (count($targets)): ?>
            <?php $i = 0; ?>
            <?php foreach ($targets as $target): ?>
                <div class="value generation-target">#<?php echo ++$i; ?></div>
                <?php if ( $target->resourceClass()): ?>
                    <div class="meta-group">
                        <h4><?php echo $translate('Class'); ?></h4>
                        <div class="value"><?php echo $escape($translate($target->resourceClass()->label())); ?></div>
                    </div>
                <?php endif; ?>
                <?php // Note: when type + value, it is a selector. ?>
                <?php echo $target->displayValues(); ?>
            <?php endforeach; ?>
        <?php else: ?>
            <p class="no-resources"><?php echo $translate('This generation has no targets.')?></p>
        <?php endif; ?>
    </div>
</div>

<?php $this->trigger('view.show.after'); ?>
